const jobs = [
    {
      title: "Full Stack Developer",
      category: "Software",
      type: "Full-time",
      description: "Participate in the entire app lifecycle, focusing on coding and debugging. Write clean code to develop functional web applications.",
      location: "San Francisco, CA",
      salary: "$115k - $140k",
      companyName: "DevTech",
      companyLogo: "/static/images/devtech_logo.png",
    },
    {
      title: "Marketing Coordinator",
      category: "Marketing",
      type: "Part-time",
      description: "Implement marketing and advertising campaigns by assembling and analyzing sales forecasts. Prepare marketing reports by collecting and summarizing sales data.",
      location: "Austin, TX",
      salary: "$40k - $50k",
      companyName: "MarketGurus",
      companyLogo: "/static/images/marketgurus_logo.png",
    },
    {
      title: "Data Analyst",
      category: "Data",
      type: "Remote",
      description: "Interpret data, analyze results using statistical techniques and provide ongoing reports. Develop and implement databases, data collection systems.",
      location: "Remote",
      salary: "$70k - $90k",
      companyName: "DataWiz",
      companyLogo: "/static/images/datawiz_logo.png",
    },
    {
      title: "Human Resources Manager",
      category: "HR",
      type: "Full-time",
      description: "Develop and implement HR strategies and initiatives aligned with the overall business strategy. Bridge management and employee relations.",
      location: "New York, NY",
      salary: "$95k - $120k",
      companyName: "PeopleFirst",
      companyLogo: "/static/images/peoplefirst_logo.png",
    },
    {
      title: "UX/UI Designer",
      category: "Design",
      type: "Freelance",
      description: "Gather and evaluate user requirements in collaboration with product managers and engineers. Illustrate design ideas using storyboards, process flows, and sitemaps.",
      location: "Remote",
      salary: "$50 per hour",
      companyName: "CreativeSolutions",
      companyLogo: "/static/images/creativesolutions_logo.png",
    },
    {
      title: "Sales Executive",
      category: "Sales",
      type: "Full-time",
      description: "Drive sustainable financial growth through boosting sales and forging strong relationships with clients. Identify emerging markets and market shifts.",
      location: "Chicago, IL",
      salary: "$80k - $100k",
      companyName: "SalesDrive",
      companyLogo: "/static/images/salesdrive_logo.png",
    }
  ];
  
  export default jobs;
  